name: 'Docker Publish'

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - master
  schedule:
    - cron: '0 0 10,20,30 * *'

permissions:
  packages: write

jobs:
  publish-stable:
    name: Docker Publish

    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'schedule' && !contains(github.ref, '-') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7'
          push: true
          tags: |
            ghcr.io/rockiestar-inc/rclone-backup-pg-17:latest
            ghcr.io/rockiestar-inc/rclone-backup-pg-17:${{ env.TAG }}

  publish-beta:
    name: Docker Publish Beta

    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'schedule' && contains(github.ref, '-') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7'
          push: true
          tags: |
            ghcr.io/rockiestar-inc/rclone-backup-pg-17:${{ env.TAG }}

  publish-master:
    name: Docker Publish Master

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7'
          push: true
          tags: |
            ghcr.io/rockiestar-inc/rclone-backup-pg-17:master
